fix: compile errors (#1193)
* fix: error TS7006 Parameter X implicitly has an any type

* fix: arg of type unknown is not assignable to parameter of type x

fix: catch clause variable cannot have type annotation

* fix: fixed more compile errors

* fix: eslint fixes

* fix: property every does not exist on type never

* fix: eslint fix

* fix: property productId does not exist on type object

* fix: property label does not exist on type object

* fix: eslint fixes

* fix: remove isObject check

* fix: split else if to own if

* fix: force params as any

* fix: remove force params as any

* fix(lint): update alcalzone-shared, merge changes from 159602d7

* style: fix nits, don't remove unknown annotation on errors

* fix: test if machine is initialized before stopping it

Co-authored-by: Dominic Griesel <d.griesel@gmx.net>